# Copyright 2019 The Forseti Security Authors. All rights reserved.
#
# Licensed under the Apache License, Versisn 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- define "spec.pod.configValidator" }}
initContainers:
{{- if .Values.policyLibrary.repositoryURL }}
{{- include "spec.container.gitSync.once" . }}
{{- else if .Values.policyLibrary.bucket }}
{{- include "spec.container.gsutilInit" . }}
{{- else }}
{{- include "spec.container.emptyDir" . }}
{{- end }}
containers:
{{- include "spec.container.configValidator" . }}
{{- if and (.Values.policyLibrary.gitSync.enabled) (.Values.policyLibrary.repositoryURL) }}
{{- include "spec.container.gitSync.periodic" . }}
{{- include "spec.container.kubeProxy" . }}
{{- end }}
securityContext:
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65533
volumes:
- name: policy-library
  emptyDir: {
      medium: "Memory"
  }
{{- if .Values.policyLibrary.gitSync.privateSSHKey }}
- name: git-sync-ssh-key
  secret: 
    secretName: git-sync-ssh-key
{{- end }}
{{- end }}
